name: moringa_project_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: GlacialIndifference
      fonts:
        - asset: assets/images/fonts/GlacialIndifference-Bold.otf
        - asset: assets/images/fonts/GlacialIndifference-Italic.otf
        - asset: assets/images/fonts/GlacialIndifference-Regular.otf